env:
  global:
  - TERM=dumb
language: java
jdk:
  - oraclejdk8

branches:
  only:
    - master
install: /bin/true
script:
  - echo "travis_fold:start:SCRIPT folding starts"
  - mvn clean
  - mvn compile
  - echo "travis_fold:end:SCRIPT folding ends"
  - mvn test install
#script: "mvn clean install -DcreateChecksum=true"
#script:
#  ./run-rdfunit.sh
notifications:
  email:
    recipients:
      - gpublio@gmail.com
      - hellmann@informatik.uni-leipzig.de
    on_success: change
    on_failure: change
