env:
  global:
  - TERM=dumb
language: java
jdk:
  - oraclejdk8

branches:
  only:
    - master
install: /bin/true
script: "mvn clean install"
#script: "mvn clean install -DcreateChecksum=true"
#script:
#  ./run-rdfunit.sh
notifications:
  email:
    recipients:
      - gpublio@gmail.com
      - hellmann@informatik.uni-leipzig.de
    on_success: change
    on_failure: change
